# General Settings
name: Terence Tham
job_title: Principal Software Engineer
email: ttham@icloud-dot-com
description: I am using cloud-based techonology to build great products that people loves to use.I also enjoy playing a round of golf, cooking delicious food, having new gadgets and making stunning photos and short videos with a camera. 
avatar: https://pbs.twimg.com/profile_images/969771290134380545/_qZ6bK8u_400x400.jpg
favicon: /favicon.ico
twitter_handler: ttham
analytics_code: UA-48115281-10
disqus: amusingcloud

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'https://twitter.com/ttham' }
-  { name: instagram, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/terencet' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: 'https://www.youtube.com/channel/UCtc2PXpuFjGu1XQEDokl-Mg' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: 'https://500px.com/ttham' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://amusing.cloud"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

